//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsentrZanyatosti
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankSet
    {
        public int id { get; set; }
        public string Job { get; set; }
        public string Income { get; set; }
        public string Need { get; set; }
        public string Arranged { get; set; }
        public int idEmployer { get; set; }
    
        public virtual EmployerSet EmployerSet { get; set; }
    }
}
