//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsentrZanyatosti
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZanyatostEntities1 : DbContext
    {
        public ZanyatostEntities1()
            : base("name=ZanyatostEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankSet> BankSet { get; set; }
        public virtual DbSet<CitizenSet> CitizenSet { get; set; }
        public virtual DbSet<EmployerSet> EmployerSet { get; set; }
        public virtual DbSet<PaySet> PaySet { get; set; }
        public virtual DbSet<ReceptionSet> ReceptionSet { get; set; }
        public virtual DbSet<StaffSet> StaffSet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
