//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsentrZanyatosti
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionSet
    {
        public int id { get; set; }
        public string service { get; set; }
        public string date { get; set; }
        public int idCitizen { get; set; }
        public int idStaff { get; set; }
    
        public virtual CitizenSet CitizenSet { get; set; }
        public virtual StaffSet StaffSet { get; set; }
    }
}
